"""wallet and ledger

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def _ledger_triggers(create: bool) -> None:
    """Ledger-i refuzon UPDATE/DELETE/TRUNCATE edhe nga SQL i drejtpërdrejtë (PostgreSQL)."""
    if op.get_bind().dialect.name != "postgresql":
        return
    if not create:
        op.execute("DROP TRIGGER IF EXISTS trg_sms_ledger_immutable ON sms_ledger_entries")
        op.execute("DROP TRIGGER IF EXISTS trg_sms_ledger_no_truncate ON sms_ledger_entries")
        op.execute("DROP FUNCTION IF EXISTS sms_forbid_mutation()")
        return
    op.execute(
        "CREATE OR REPLACE FUNCTION sms_forbid_mutation() RETURNS trigger AS $$ "
        "BEGIN RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = '55000'; "
        "END; $$ LANGUAGE plpgsql"
    )
    op.execute(
        "CREATE TRIGGER trg_sms_ledger_immutable BEFORE UPDATE OR DELETE ON sms_ledger_entries "
        "FOR EACH ROW EXECUTE FUNCTION sms_forbid_mutation()"
    )
    op.execute(
        "CREATE TRIGGER trg_sms_ledger_no_truncate BEFORE TRUNCATE ON sms_ledger_entries "
        "FOR EACH STATEMENT EXECUTE FUNCTION sms_forbid_mutation()"
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_wallets",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_wallets")),
        sa.UniqueConstraint("owner_ref", "currency", name=op.f("uq_sms_wallets_owner_ref")),
    )
    op.create_index(op.f("ix_sms_wallets_owner_ref"), "sms_wallets", ["owner_ref"], unique=False)
    op.create_table(
        "sms_holds",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "wallet_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("captured_amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "CAPTURED", "RELEASED", name="holdstatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("reference", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_sms_holds_amount_positive")),
        sa.ForeignKeyConstraint(
            ["wallet_id"], ["sms_wallets.id"], name=op.f("fk_sms_holds_wallet_id_sms_wallets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_holds")),
        sa.UniqueConstraint("wallet_id", "reference", name=op.f("uq_sms_holds_wallet_id")),
    )
    op.create_index(op.f("ix_sms_holds_wallet_id"), "sms_holds", ["wallet_id"], unique=False)
    op.create_table(
        "sms_ledger_entries",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "wallet_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "entry_type",
            sa.Enum(
                "TOPUP",
                "HOLD",
                "CAPTURE",
                "RELEASE",
                "REFUND",
                "ADJUSTMENT",
                name="entrytype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("available_delta", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("held_delta", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("available_after", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("held_after", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("ref_type", sa.String(length=32), nullable=True),
        sa.Column("ref_id", sa.String(length=64), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "available_after >= 0", name=op.f("ck_sms_ledger_entries_available_non_negative")
        ),
        sa.CheckConstraint("held_after >= 0", name=op.f("ck_sms_ledger_entries_held_non_negative")),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["sms_wallets.id"],
            name=op.f("fk_sms_ledger_entries_wallet_id_sms_wallets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_ledger_entries")),
        sa.UniqueConstraint(
            "wallet_id", "idempotency_key", name=op.f("uq_sms_ledger_entries_wallet_id")
        ),
    )
    op.create_index(
        "ix_sms_ledger_entries_wallet_id_id",
        "sms_ledger_entries",
        ["wallet_id", "id"],
        unique=False,
    )
    op.create_table(
        "sms_topups",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "wallet_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column(
            "method",
            sa.Enum("CASH", "ELECTRONIC", name="topupmethod", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "CONFIRMED", "FAILED", name="topupstatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("external_ref", sa.String(length=128), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount > 0", name=op.f("ck_sms_topups_amount_positive")),
        sa.ForeignKeyConstraint(
            ["wallet_id"], ["sms_wallets.id"], name=op.f("fk_sms_topups_wallet_id_sms_wallets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_topups")),
        sa.UniqueConstraint("external_ref", name=op.f("uq_sms_topups_external_ref")),
    )
    op.create_index(op.f("ix_sms_topups_wallet_id"), "sms_topups", ["wallet_id"], unique=False)
    # ### end Alembic commands ###
    _ledger_triggers(create=True)


def downgrade() -> None:
    _ledger_triggers(create=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sms_topups_wallet_id"), table_name="sms_topups")
    op.drop_table("sms_topups")
    op.drop_index("ix_sms_ledger_entries_wallet_id_id", table_name="sms_ledger_entries")
    op.drop_table("sms_ledger_entries")
    op.drop_index(op.f("ix_sms_holds_wallet_id"), table_name="sms_holds")
    op.drop_table("sms_holds")
    op.drop_index(op.f("ix_sms_wallets_owner_ref"), table_name="sms_wallets")
    op.drop_table("sms_wallets")
    # ### end Alembic commands ###
