"""rate cards

Revision ID: 0002
Revises: 0001
"""

import sqlalchemy as sa
from alembic import op


revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_rate_cards",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_rate_cards")),
        sa.UniqueConstraint("name", name=op.f("uq_sms_rate_cards_name")),
    )
    op.create_table(
        "sms_rate_card_versions",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "rate_card_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", name="versionstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["rate_card_id"],
            ["sms_rate_cards.id"],
            name=op.f("fk_sms_rate_card_versions_rate_card_id_sms_rate_cards"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_rate_card_versions")),
        sa.UniqueConstraint(
            "rate_card_id", "version", name=op.f("uq_sms_rate_card_versions_rate_card_id")
        ),
    )
    op.create_index(
        "ix_sms_rcv_card_effective",
        "sms_rate_card_versions",
        ["rate_card_id", "status", "effective_from"],
        unique=False,
    )
    op.create_table(
        "sms_rates",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "version_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("operator", sa.String(length=8), nullable=False),
        sa.Column("price_per_segment", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.CheckConstraint("price_per_segment >= 0", name=op.f("ck_sms_rates_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["sms_rate_card_versions.id"],
            name=op.f("fk_sms_rates_version_id_sms_rate_card_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_rates")),
        sa.UniqueConstraint(
            "version_id", "prefix", "operator", name=op.f("uq_sms_rates_version_id")
        ),
    )
    op.create_index(
        "ix_sms_rates_version_prefix", "sms_rates", ["version_id", "prefix"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sms_rates_version_prefix", table_name="sms_rates")
    op.drop_table("sms_rates")
    op.drop_index("ix_sms_rcv_card_effective", table_name="sms_rate_card_versions")
    op.drop_table("sms_rate_card_versions")
    op.drop_table("sms_rate_cards")
    # ### end Alembic commands ###
