"""sender ids and templates

Revision ID: 0003
Revises: 0002
"""

import sqlalchemy as sa
from alembic import op


revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_sender_ids",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("value", sa.String(length=16), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("ALPHANUMERIC", "NUMERIC", name="senderkind", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "REVOKED",
                name="approvalstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("approved_key", sa.String(length=32), nullable=True),
        sa.Column("reviewed_by", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_sender_ids")),
        sa.UniqueConstraint("approved_key", name=op.f("uq_sms_sender_ids_approved_key")),
        sa.UniqueConstraint(
            "owner_ref", "country", "value", name=op.f("uq_sms_sender_ids_owner_ref")
        ),
    )
    op.create_index(
        op.f("ix_sms_sender_ids_owner_ref"), "sms_sender_ids", ["owner_ref"], unique=False
    )
    op.create_table(
        "sms_templates",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_templates")),
        sa.UniqueConstraint("owner_ref", "name", name=op.f("uq_sms_templates_owner_ref")),
    )
    op.create_table(
        "sms_template_versions",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "template_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "REVOKED",
                name="approvalstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.String(length=64), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["sms_templates.id"],
            name=op.f("fk_sms_template_versions_template_id_sms_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_template_versions")),
        sa.UniqueConstraint(
            "template_id", "version", name=op.f("uq_sms_template_versions_template_id")
        ),
    )
    op.create_index(
        "ix_sms_tv_template_status",
        "sms_template_versions",
        ["template_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sms_tv_template_status", table_name="sms_template_versions")
    op.drop_table("sms_template_versions")
    op.drop_table("sms_templates")
    op.drop_index(op.f("ix_sms_sender_ids_owner_ref"), table_name="sms_sender_ids")
    op.drop_table("sms_sender_ids")
    # ### end Alembic commands ###
