"""sending pipeline

Revision ID: 0004
Revises: 0003
"""

import sqlalchemy as sa
from alembic import op


revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_routes",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_routes")),
        sa.UniqueConstraint("prefix", "provider", name=op.f("uq_sms_routes_prefix")),
    )
    op.create_table(
        "sms_account_plans",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column(
            "rate_card_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rate_card_id"],
            ["sms_rate_cards.id"],
            name=op.f("fk_sms_account_plans_rate_card_id_sms_rate_cards"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_account_plans")),
        sa.UniqueConstraint("owner_ref", name=op.f("uq_sms_account_plans_owner_ref")),
    )
    op.create_table(
        "sms_messages",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "wallet_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("hold_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("sender", sa.String(length=16), nullable=False),
        sa.Column("destination", sa.String(length=16), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "template_version_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("encoding", sa.String(length=8), nullable=False),
        sa.Column("segments", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column(
            "rate_version_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("rate_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_message_id", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "SENDING",
                "SENT",
                "DELIVERED",
                "FAILED",
                name="messagestatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["hold_id"], ["sms_holds.id"], name=op.f("fk_sms_messages_hold_id_sms_holds")
        ),
        sa.ForeignKeyConstraint(
            ["rate_id"], ["sms_rates.id"], name=op.f("fk_sms_messages_rate_id_sms_rates")
        ),
        sa.ForeignKeyConstraint(
            ["rate_version_id"],
            ["sms_rate_card_versions.id"],
            name=op.f("fk_sms_messages_rate_version_id_sms_rate_card_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["template_version_id"],
            ["sms_template_versions.id"],
            name=op.f("fk_sms_messages_template_version_id_sms_template_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"], ["sms_wallets.id"], name=op.f("fk_sms_messages_wallet_id_sms_wallets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_messages")),
        sa.UniqueConstraint("owner_ref", "idempotency_key", name=op.f("uq_sms_messages_owner_ref")),
        sa.UniqueConstraint("public_id", name=op.f("uq_sms_messages_public_id")),
    )
    op.create_index(
        "ix_sms_messages_provider_msg",
        "sms_messages",
        ["provider", "provider_message_id"],
        unique=False,
    )
    op.create_index(
        "ix_sms_messages_queue", "sms_messages", ["status", "next_attempt_at"], unique=False
    )
    op.create_table(
        "sms_message_events",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "message_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["sms_messages.id"],
            name=op.f("fk_sms_message_events_message_id_sms_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_message_events")),
    )
    op.create_index(
        op.f("ix_sms_message_events_message_id"), "sms_message_events", ["message_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sms_message_events_message_id"), table_name="sms_message_events")
    op.drop_table("sms_message_events")
    op.drop_index("ix_sms_messages_queue", table_name="sms_messages")
    op.drop_index("ix_sms_messages_provider_msg", table_name="sms_messages")
    op.drop_table("sms_messages")
    op.drop_table("sms_account_plans")
    op.drop_table("sms_routes")
    # ### end Alembic commands ###
