"""dlr receipts

Revision ID: 0005
Revises: 0004
"""

import sqlalchemy as sa
from alembic import op


revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_dlr_receipts",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_message_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=True),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("raw_body", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_dlr_receipts")),
    )
    op.create_index(
        "ix_sms_dlr_receipts_pmid",
        "sms_dlr_receipts",
        ["provider", "provider_message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sms_dlr_receipts_pmid", table_name="sms_dlr_receipts")
    op.drop_table("sms_dlr_receipts")
    # ### end Alembic commands ###
