"""admin rbac audit switches

Revision ID: 0006
Revises: 0005
"""

import sqlalchemy as sa
from alembic import op


revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def _audit_triggers(create: bool) -> None:
    """Audit log-u është vetëm-shtim edhe nga SQL i drejtpërdrejtë (PostgreSQL)."""
    if op.get_bind().dialect.name != "postgresql":
        return
    if not create:
        op.execute("DROP TRIGGER IF EXISTS trg_sms_audit_immutable ON sms_audit_log")
        op.execute("DROP TRIGGER IF EXISTS trg_sms_audit_no_truncate ON sms_audit_log")
        return
    op.execute(
        "CREATE OR REPLACE FUNCTION sms_forbid_mutation() RETURNS trigger AS $$ "
        "BEGIN RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = '55000'; "
        "END; $$ LANGUAGE plpgsql"
    )
    op.execute(
        "CREATE TRIGGER trg_sms_audit_immutable BEFORE UPDATE OR DELETE ON sms_audit_log "
        "FOR EACH ROW EXECUTE FUNCTION sms_forbid_mutation()"
    )
    op.execute(
        "CREATE TRIGGER trg_sms_audit_no_truncate BEFORE TRUNCATE ON sms_audit_log "
        "FOR EACH STATEMENT EXECUTE FUNCTION sms_forbid_mutation()"
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_api_keys",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("prefix", sa.String(length=12), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("owner_ref", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "REVOKED", name="keystatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_api_keys")),
        sa.UniqueConstraint("prefix", name=op.f("uq_sms_api_keys_prefix")),
    )
    op.create_table(
        "sms_audit_log",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_audit_log")),
    )
    op.create_index("ix_sms_audit_actor", "sms_audit_log", ["actor"], unique=False)
    op.create_index(
        "ix_sms_audit_target", "sms_audit_log", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "sms_switches",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=64), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_sms_switches")),
    )
    op.add_column("sms_account_plans", sa.Column("rate_limit_per_min", sa.Integer(), nullable=True))
    op.create_index(
        "ix_sms_messages_owner_created", "sms_messages", ["owner_ref", "created_at"], unique=False
    )
    # ### end Alembic commands ###
    _audit_triggers(create=True)


def downgrade() -> None:
    _audit_triggers(create=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sms_messages_owner_created", table_name="sms_messages")
    op.drop_column("sms_account_plans", "rate_limit_per_min")
    op.drop_table("sms_switches")
    op.drop_index("ix_sms_audit_target", table_name="sms_audit_log")
    op.drop_index("ix_sms_audit_actor", table_name="sms_audit_log")
    op.drop_table("sms_audit_log")
    op.drop_table("sms_api_keys")
    # ### end Alembic commands ###
