"""contacts and consent

Revision ID: 0008
Revises: 0007
"""

import sqlalchemy as sa
from alembic import op


revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def _consent_triggers(create: bool) -> None:
    """Prova e consent-it është vetëm-shtim edhe nga SQL i drejtpërdrejtë (PostgreSQL)."""
    if op.get_bind().dialect.name != "postgresql":
        return
    if not create:
        op.execute("DROP TRIGGER IF EXISTS trg_sms_consent_immutable ON sms_consent_events")
        op.execute("DROP TRIGGER IF EXISTS trg_sms_consent_no_truncate ON sms_consent_events")
        return
    op.execute(
        "CREATE OR REPLACE FUNCTION sms_forbid_mutation() RETURNS trigger AS $$ "
        "BEGIN RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = '55000'; "
        "END; $$ LANGUAGE plpgsql"
    )
    op.execute(
        "CREATE TRIGGER trg_sms_consent_immutable BEFORE UPDATE OR DELETE ON sms_consent_events "
        "FOR EACH ROW EXECUTE FUNCTION sms_forbid_mutation()"
    )
    op.execute(
        "CREATE TRIGGER trg_sms_consent_no_truncate BEFORE TRUNCATE ON sms_consent_events "
        "FOR EACH STATEMENT EXECUTE FUNCTION sms_forbid_mutation()"
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_consent_events",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("channel", sa.String(length=8), nullable=False),
        sa.Column("address_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "action",
            sa.Enum("OPT_IN", "OPT_OUT", name="consentaction", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=48), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_consent_events")),
    )
    op.create_index(
        "ix_sms_consent_events_lookup",
        "sms_consent_events",
        ["owner_ref", "channel", "address_hash"],
        unique=False,
    )
    op.create_table(
        "sms_contact_lists",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_contact_lists")),
        sa.UniqueConstraint("owner_ref", "name", name=op.f("uq_sms_contact_lists_owner_ref")),
    )
    op.create_table(
        "sms_contacts",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("phone", sa.String(length=16), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("first_name", sa.String(length=64), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ERASED", name="contactstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status = 'ERASED' OR phone IS NOT NULL OR email IS NOT NULL",
            name=op.f("ck_sms_contacts_has_address"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_contacts")),
        sa.UniqueConstraint("owner_ref", "email", name="uq_sms_contacts_owner_email"),
        sa.UniqueConstraint("owner_ref", "external_id", name="uq_sms_contacts_owner_external"),
        sa.UniqueConstraint("owner_ref", "phone", name="uq_sms_contacts_owner_phone"),
    )
    op.create_index("ix_sms_contacts_owner_id", "sms_contacts", ["owner_ref", "id"], unique=False)
    op.create_table(
        "sms_consent_state",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("channel", sa.String(length=8), nullable=False),
        sa.Column("address_hash", sa.String(length=64), nullable=False),
        sa.Column("opted_in", sa.Boolean(), nullable=False),
        sa.Column("hard", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=24), nullable=False),
        sa.Column(
            "last_event_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["last_event_id"],
            ["sms_consent_events.id"],
            name=op.f("fk_sms_consent_state_last_event_id_sms_consent_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_consent_state")),
        sa.UniqueConstraint(
            "owner_ref", "channel", "address_hash", name=op.f("uq_sms_consent_state_owner_ref")
        ),
    )
    op.create_table(
        "sms_list_members",
        sa.Column("list_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "contact_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["sms_contacts.id"],
            name=op.f("fk_sms_list_members_contact_id_sms_contacts"),
        ),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["sms_contact_lists.id"],
            name=op.f("fk_sms_list_members_list_id_sms_contact_lists"),
        ),
        sa.PrimaryKeyConstraint("list_id", "contact_id", name=op.f("pk_sms_list_members")),
    )
    op.create_index("ix_sms_list_members_contact", "sms_list_members", ["contact_id"], unique=False)
    op.add_column(
        "sms_messages",
        sa.Column("category", sa.String(length=16), server_default="transactional", nullable=False),
    )
    # ### end Alembic commands ###
    _consent_triggers(create=True)


def downgrade() -> None:
    _consent_triggers(create=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sms_messages", "category")
    op.drop_index("ix_sms_list_members_contact", table_name="sms_list_members")
    op.drop_table("sms_list_members")
    op.drop_table("sms_consent_state")
    op.drop_index("ix_sms_contacts_owner_id", table_name="sms_contacts")
    op.drop_table("sms_contacts")
    op.drop_table("sms_contact_lists")
    op.drop_index("ix_sms_consent_events_lookup", table_name="sms_consent_events")
    op.drop_table("sms_consent_events")
    # ### end Alembic commands ###
