"""campaigns

Revision ID: 0009
Revises: 0008
"""

import sqlalchemy as sa
from alembic import op


revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_campaigns",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("list_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("sender", sa.String(length=16), nullable=False),
        sa.Column("text", sa.String(length=1600), nullable=True),
        sa.Column(
            "template_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SCHEDULED",
                "PREPARING",
                "RUNNING",
                "PAUSED",
                "COMPLETED",
                "CANCELLED",
                name="campaignstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_cost", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("rate_per_minute", sa.Integer(), nullable=False),
        sa.Column("window_start_hour", sa.Integer(), nullable=True),
        sa.Column("window_end_hour", sa.Integer(), nullable=True),
        sa.Column("utc_offset_minutes", sa.Integer(), nullable=False),
        sa.Column("prep_cursor", sa.BigInteger(), nullable=False),
        sa.Column("pause_reason", sa.String(length=32), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(text IS NOT NULL) <> (template_id IS NOT NULL)",
            name=op.f("ck_sms_campaigns_text_xor_template"),
        ),
        sa.CheckConstraint(
            "rate_per_minute BETWEEN 1 AND 10000", name=op.f("ck_sms_campaigns_rate_range")
        ),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["sms_contact_lists.id"],
            name=op.f("fk_sms_campaigns_list_id_sms_contact_lists"),
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["sms_templates.id"],
            name=op.f("fk_sms_campaigns_template_id_sms_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_campaigns")),
        sa.UniqueConstraint("owner_ref", "name", name="uq_sms_campaigns_owner_name"),
    )
    op.create_index("ix_sms_campaigns_status", "sms_campaigns", ["status", "id"], unique=False)
    op.create_table(
        "sms_campaign_recipients",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "campaign_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "contact_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("address", sa.String(length=16), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "SKIPPED",
                "CANCELLED",
                name="recipientstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=48), nullable=True),
        sa.Column(
            "message_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["sms_campaigns.id"],
            name=op.f("fk_sms_campaign_recipients_campaign_id_sms_campaigns"),
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["sms_contacts.id"],
            name=op.f("fk_sms_campaign_recipients_contact_id_sms_contacts"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["sms_messages.id"],
            name=op.f("fk_sms_campaign_recipients_message_id_sms_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_campaign_recipients")),
        sa.UniqueConstraint("campaign_id", "contact_id", name="uq_sms_camp_recipient"),
    )
    op.create_index(
        "ix_sms_camp_recipients_contact", "sms_campaign_recipients", ["contact_id"], unique=False
    )
    op.create_index(
        "ix_sms_camp_recipients_message", "sms_campaign_recipients", ["message_id"], unique=False
    )
    op.create_index(
        "ix_sms_camp_recipients_status",
        "sms_campaign_recipients",
        ["campaign_id", "status", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sms_camp_recipients_status", table_name="sms_campaign_recipients")
    op.drop_index("ix_sms_camp_recipients_message", table_name="sms_campaign_recipients")
    op.drop_index("ix_sms_camp_recipients_contact", table_name="sms_campaign_recipients")
    op.drop_table("sms_campaign_recipients")
    op.drop_index("ix_sms_campaigns_status", table_name="sms_campaigns")
    op.drop_table("sms_campaigns")
    # ### end Alembic commands ###
