"""email

Revision ID: 0010
Revises: 0009
"""

import sqlalchemy as sa
from alembic import op


revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


def _triggers(create: bool) -> None:
    """Historiku i statuseve të email-it është vetëm-shtim edhe nga SQL i drejtpërdrejtë."""
    if op.get_bind().dialect.name != "postgresql":
        return
    if not create:
        op.execute("DROP TRIGGER IF EXISTS trg_sms_email_events_immutable ON sms_email_events")
        op.execute("DROP TRIGGER IF EXISTS trg_sms_email_events_no_truncate ON sms_email_events")
        return
    op.execute(
        "CREATE OR REPLACE FUNCTION sms_forbid_mutation() RETURNS trigger AS $$ "
        "BEGIN RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = '55000'; "
        "END; $$ LANGUAGE plpgsql"
    )
    op.execute(
        "CREATE TRIGGER trg_sms_email_events_immutable BEFORE UPDATE OR DELETE "
        "ON sms_email_events FOR EACH ROW EXECUTE FUNCTION sms_forbid_mutation()"
    )
    op.execute(
        "CREATE TRIGGER trg_sms_email_events_no_truncate BEFORE TRUNCATE "
        "ON sms_email_events FOR EACH STATEMENT EXECUTE FUNCTION sms_forbid_mutation()"
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_email_domains",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=190), nullable=False),
        sa.Column("dkim_selector", sa.String(length=32), nullable=False),
        sa.Column("dkim_public_key", sa.Text(), nullable=False),
        sa.Column("dkim_private_key_enc", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "VERIFIED", name="domainstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("verified_key", sa.String(length=190), nullable=True),
        sa.Column("spf_ok", sa.Boolean(), nullable=False),
        sa.Column("dkim_ok", sa.Boolean(), nullable=False),
        sa.Column("dmarc_ok", sa.Boolean(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_email_domains")),
        sa.UniqueConstraint("owner_ref", "domain", name="uq_sms_email_domains_owner"),
        sa.UniqueConstraint("verified_key", name=op.f("uq_sms_email_domains_verified_key")),
    )
    op.create_table(
        "sms_emails",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column(
            "domain_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("from_email", sa.String(length=254), nullable=False),
        sa.Column("from_name", sa.String(length=100), nullable=True),
        sa.Column("to_email", sa.String(length=254), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("text_body", sa.Text(), nullable=False),
        sa.Column("html_body", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_message_id", sa.String(length=190), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "SENDING",
                "SENT",
                "DELIVERED",
                "BOUNCED",
                "COMPLAINED",
                "FAILED",
                name="emailstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["sms_email_domains.id"],
            name=op.f("fk_sms_emails_domain_id_sms_email_domains"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_emails")),
        sa.UniqueConstraint("owner_ref", "idempotency_key", name="uq_sms_emails_idem"),
        sa.UniqueConstraint("public_id", name=op.f("uq_sms_emails_public_id")),
    )
    op.create_index(
        "ix_sms_emails_owner_created", "sms_emails", ["owner_ref", "created_at"], unique=False
    )
    op.create_index(
        "ix_sms_emails_provider_msg",
        "sms_emails",
        ["provider", "provider_message_id"],
        unique=False,
    )
    op.create_index(
        "ix_sms_emails_queue", "sms_emails", ["status", "next_attempt_at"], unique=False
    )
    op.create_table(
        "sms_email_events",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("email_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("from_status", sa.String(length=16), nullable=True),
        sa.Column("to_status", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["email_id"], ["sms_emails.id"], name=op.f("fk_sms_email_events_email_id_sms_emails")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_email_events")),
    )
    op.create_index(
        op.f("ix_sms_email_events_email_id"), "sms_email_events", ["email_id"], unique=False
    )
    op.add_column(
        "sms_account_plans", sa.Column("email_rate_limit_per_min", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###
    _triggers(create=True)


def downgrade() -> None:
    _triggers(create=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sms_account_plans", "email_rate_limit_per_min")
    op.drop_index(op.f("ix_sms_email_events_email_id"), table_name="sms_email_events")
    op.drop_table("sms_email_events")
    op.drop_index("ix_sms_emails_queue", table_name="sms_emails")
    op.drop_index("ix_sms_emails_provider_msg", table_name="sms_emails")
    op.drop_index("ix_sms_emails_owner_created", table_name="sms_emails")
    op.drop_table("sms_emails")
    op.drop_table("sms_email_domains")
    # ### end Alembic commands ###
