"""events and webhooks

Revision ID: 0012
Revises: 0011
"""

import sqlalchemy as sa
from alembic import op


revision = "0012"
down_revision = "0011"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_events",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=48), nullable=False),
        sa.Column("resource_type", sa.String(length=24), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_events")),
    )
    op.create_index("ix_sms_events_created", "sms_events", ["created_at"], unique=False)
    op.create_index("ix_sms_events_owner_id", "sms_events", ["owner_ref", "id"], unique=False)
    op.create_table(
        "sms_webhook_endpoints",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("secret_enc", sa.Text(), nullable=False),
        sa.Column("event_types", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DISABLED", name="endpointstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("disabled_reason", sa.String(length=64), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_webhook_endpoints")),
    )
    op.create_index(
        op.f("ix_sms_webhook_endpoints_owner_ref"),
        "sms_webhook_endpoints",
        ["owner_ref"],
        unique=False,
    )
    op.create_table(
        "sms_webhook_deliveries",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "endpoint_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("event_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCEEDED",
                "FAILED",
                name="deliverystatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_status_code", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.String(length=120), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["sms_webhook_endpoints.id"],
            name=op.f("fk_sms_webhook_deliveries_endpoint_id_sms_webhook_endpoints"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["sms_events.id"],
            name=op.f("fk_sms_webhook_deliveries_event_id_sms_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_webhook_deliveries")),
    )
    op.create_index(
        "ix_sms_wh_deliveries_endpoint",
        "sms_webhook_deliveries",
        ["endpoint_id", "id"],
        unique=False,
    )
    op.create_index(
        "ix_sms_wh_deliveries_event", "sms_webhook_deliveries", ["event_id"], unique=False
    )
    op.create_index(
        "ix_sms_wh_deliveries_queue",
        "sms_webhook_deliveries",
        ["status", "next_attempt_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sms_wh_deliveries_queue", table_name="sms_webhook_deliveries")
    op.drop_index("ix_sms_wh_deliveries_event", table_name="sms_webhook_deliveries")
    op.drop_index("ix_sms_wh_deliveries_endpoint", table_name="sms_webhook_deliveries")
    op.drop_table("sms_webhook_deliveries")
    op.drop_index(op.f("ix_sms_webhook_endpoints_owner_ref"), table_name="sms_webhook_endpoints")
    op.drop_table("sms_webhook_endpoints")
    op.drop_index("ix_sms_events_owner_id", table_name="sms_events")
    op.drop_index("ix_sms_events_created", table_name="sms_events")
    op.drop_table("sms_events")
    # ### end Alembic commands ###
