"""billing

Revision ID: 0013
Revises: 0012
"""

import sqlalchemy as sa
from alembic import op


revision = "0013"
down_revision = "0012"
branch_labels = None
depends_on = None


FROZEN = (
    "number",
    "owner_ref",
    "subscription_id",
    "period_start",
    "period_end",
    "currency",
    "subtotal",
    "vat_rate",
    "tax",
    "total",
    "bill_to",
    "issued_at",
    "due_at",
)


def _triggers(create: bool) -> None:
    """Faturat e lëshuara: fusha financiare të pandryshueshme, statusi final, pa fshirje (PostgreSQL)."""
    if op.get_bind().dialect.name != "postgresql":
        return
    if not create:
        op.execute("DROP TRIGGER IF EXISTS trg_sms_invoices_guard ON sms_invoices")
        op.execute("DROP TRIGGER IF EXISTS trg_sms_invoices_no_delete ON sms_invoices")
        op.execute("DROP TRIGGER IF EXISTS trg_sms_invoices_no_truncate ON sms_invoices")
        op.execute("DROP TRIGGER IF EXISTS trg_sms_invoice_lines_immutable ON sms_invoice_lines")
        op.execute("DROP TRIGGER IF EXISTS trg_sms_invoice_lines_no_truncate ON sms_invoice_lines")
        op.execute("DROP FUNCTION IF EXISTS sms_invoice_guard()")
        return
    op.execute(
        "CREATE OR REPLACE FUNCTION sms_forbid_mutation() RETURNS trigger AS $$ "
        "BEGIN RAISE EXCEPTION '% is append-only', TG_TABLE_NAME USING ERRCODE = '55000'; "
        "END; $$ LANGUAGE plpgsql"
    )
    cond = " OR ".join(f"NEW.{c} IS DISTINCT FROM OLD.{c}" for c in FROZEN)
    op.execute(
        "CREATE OR REPLACE FUNCTION sms_invoice_guard() RETURNS trigger AS $$ BEGIN "
        f"IF {cond} THEN RAISE EXCEPTION 'invoice % is immutable', OLD.number "
        "USING ERRCODE = '55000'; END IF; "
        "IF OLD.status <> 'OPEN' AND NEW.status IS DISTINCT FROM OLD.status THEN "
        "RAISE EXCEPTION 'invoice % status is final', OLD.number USING ERRCODE = '55000'; "
        "END IF; RETURN NEW; END; $$ LANGUAGE plpgsql"
    )
    op.execute(
        "CREATE TRIGGER trg_sms_invoices_guard BEFORE UPDATE ON sms_invoices "
        "FOR EACH ROW EXECUTE FUNCTION sms_invoice_guard()"
    )
    op.execute(
        "CREATE TRIGGER trg_sms_invoices_no_delete BEFORE DELETE ON sms_invoices "
        "FOR EACH ROW EXECUTE FUNCTION sms_forbid_mutation()"
    )
    op.execute(
        "CREATE TRIGGER trg_sms_invoices_no_truncate BEFORE TRUNCATE ON sms_invoices "
        "FOR EACH STATEMENT EXECUTE FUNCTION sms_forbid_mutation()"
    )
    op.execute(
        "CREATE TRIGGER trg_sms_invoice_lines_immutable BEFORE UPDATE OR DELETE ON sms_invoice_lines "
        "FOR EACH ROW EXECUTE FUNCTION sms_forbid_mutation()"
    )
    op.execute(
        "CREATE TRIGGER trg_sms_invoice_lines_no_truncate BEFORE TRUNCATE ON sms_invoice_lines "
        "FOR EACH STATEMENT EXECUTE FUNCTION sms_forbid_mutation()"
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_billing_profiles",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("legal_name", sa.String(length=120), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("tax_id", sa.String(length=40), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "vat_rate >= 0 AND vat_rate <= 1", name=op.f("ck_sms_billing_profiles_vat_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_billing_profiles")),
        sa.UniqueConstraint("owner_ref", name=op.f("uq_sms_billing_profiles_owner_ref")),
    )
    op.create_table(
        "sms_invoice_counters",
        sa.Column("year", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("last_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("year", name=op.f("pk_sms_invoice_counters")),
    )
    op.create_table(
        "sms_plans",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("monthly_fee", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("included_emails", sa.Integer(), nullable=False),
        sa.Column("email_overage_price", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "RETIRED", name="planstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "email_overage_price >= 0", name=op.f("ck_sms_plans_overage_non_negative")
        ),
        sa.CheckConstraint("included_emails >= 0", name=op.f("ck_sms_plans_included_non_negative")),
        sa.CheckConstraint("monthly_fee >= 0", name=op.f("ck_sms_plans_fee_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_plans")),
        sa.UniqueConstraint("code", name=op.f("uq_sms_plans_code")),
    )
    op.create_table(
        "sms_subscriptions",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column("plan_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "pending_plan_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CANCELLED", name="substatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("periods_billed", sa.Integer(), nullable=False),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("auto_pay", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["pending_plan_id"],
            ["sms_plans.id"],
            name=op.f("fk_sms_subscriptions_pending_plan_id_sms_plans"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["sms_plans.id"], name=op.f("fk_sms_subscriptions_plan_id_sms_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_subscriptions")),
        sa.UniqueConstraint("owner_ref", name=op.f("uq_sms_subscriptions_owner_ref")),
    )
    op.create_table(
        "sms_invoices",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("number", sa.String(length=24), nullable=False),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column(
            "subscription_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("tax", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("total", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "PAID", "VOID", name="invoicestatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("bill_to", sa.Text(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_via", sa.String(length=24), nullable=True),
        sa.Column("voided_reason", sa.String(length=200), nullable=True),
        sa.CheckConstraint("total >= 0", name=op.f("ck_sms_invoices_total_non_negative")),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["sms_subscriptions.id"],
            name=op.f("fk_sms_invoices_subscription_id_sms_subscriptions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_invoices")),
        sa.UniqueConstraint("number", name=op.f("uq_sms_invoices_number")),
        sa.UniqueConstraint("subscription_id", "period_start", name="uq_sms_invoices_sub_period"),
    )
    op.create_index("ix_sms_invoices_owner", "sms_invoices", ["owner_ref", "id"], unique=False)
    op.create_index(
        "ix_sms_invoices_status_due", "sms_invoices", ["status", "due_at"], unique=False
    )
    op.create_table(
        "sms_invoice_lines",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "invoice_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["sms_invoices.id"],
            name=op.f("fk_sms_invoice_lines_invoice_id_sms_invoices"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_invoice_lines")),
    )
    op.create_index(
        op.f("ix_sms_invoice_lines_invoice_id"), "sms_invoice_lines", ["invoice_id"], unique=False
    )
    op.create_table(
        "sms_payments",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_ref", sa.String(length=64), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum("TOPUP", "INVOICE", name="paymentpurpose", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "invoice_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("wallet_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("amount", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("checkout_url", sa.String(length=2000), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCEEDED",
                "FAILED",
                "EXPIRED",
                name="paymentstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("failure_reason", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount > 0", name=op.f("ck_sms_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["sms_invoices.id"],
            name=op.f("fk_sms_payments_invoice_id_sms_invoices"),
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"], ["sms_wallets.id"], name=op.f("fk_sms_payments_wallet_id_sms_wallets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_payments")),
        sa.UniqueConstraint("provider", "external_id", name="uq_sms_payments_provider_ext"),
    )
    op.create_index("ix_sms_payments_owner", "sms_payments", ["owner_ref", "id"], unique=False)
    # ### end Alembic commands ###
    _triggers(create=True)


def downgrade() -> None:
    _triggers(create=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sms_payments_owner", table_name="sms_payments")
    op.drop_table("sms_payments")
    op.drop_index(op.f("ix_sms_invoice_lines_invoice_id"), table_name="sms_invoice_lines")
    op.drop_table("sms_invoice_lines")
    op.drop_index("ix_sms_invoices_status_due", table_name="sms_invoices")
    op.drop_index("ix_sms_invoices_owner", table_name="sms_invoices")
    op.drop_table("sms_invoices")
    op.drop_table("sms_subscriptions")
    op.drop_table("sms_plans")
    op.drop_table("sms_invoice_counters")
    op.drop_table("sms_billing_profiles")
    # ### end Alembic commands ###
